name: Create Release PR

on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: "Release Type"
                required: true
                default: "rc"
                type: choice
                options:
                    - rc
                    - latest

permissions:
    pull-requests: write

jobs:
    get-next-version:
        runs-on: ubuntu-latest
        steps:
            - name: Set Branch Name
              id: set-brach-name
              run: |
                  if [ "${{ github.event.inputs.releaseType }}" == "rc" ]; then
                      echo "BRANCH_NAME=homolog" >> $GITHUB_ENV
                  elif [ "${{ github.event.inputs.releaseType }}" == "latest" ]; then
                      echo "BRANCH_NAME=main" >> $GITHUB_ENV
                  fi

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_TOKEN }}
                  ref: ${{ env.BRANCH_NAME }}
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun i

            - run: GITHUB_REF=$BRANCH_NAME bunx semantic-release --dry-run --no-ci
              id: get-next-version
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        outputs:
            new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
            new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

    create-pr:
        runs-on: ubuntu-latest
        needs: get-next-version
        if: needs.get-next-version.outputs.new-release-published == 'true'
        steps:
            - uses: actions/checkout@v3
            - name: Create Release Branch
              run: |
                  git status
                  RELEASE_BRANCH=release/v${{ needs.get-next-version.outputs.new-release-version }}
                  git checkout $RELEASE_BRANCH 2>/dev/null || git checkout -b $RELEASE_BRANCH
                  git push origin $RELEASE_BRANCH

            - name: pull-request
              run: |
                  RELEASE_BRANCH=release/v${{ needs.get-next-version.outputs.new-release-version }}
                  gh pr create --base $RELEASE_BRANCH --head "$BRANCH_NAME" --title 'chore: release  v${{ needs.get-next-version.outputs.new-release-version }}' --body 'Created by Github action'
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
