on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: "Release Type"
                required: true
                default: "rc"
                type: choice
                options:
                    - rc
                    - latest

permissions:
    pull-requests: write

jobs:
    get-next-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.inputs.releaseType == 'rc' && 'homolog' || github.event.inputs.releaseType == 'latest' && 'main' }}

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun i

            - run: bunx semantic-release --dry-run
              id: get-next-version
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        outputs:
            new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
            new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

    create-pr:
        runs-on: ubuntu-latest
        needs: get-next-version
        if: needs.get-next-version.outputs.new-release-published == 'true'
        steps:
            - uses: actions/checkout@v3
            - name: Create Release Branch
              run: |
                  RELEASE_BRANCH=release/v${{ needs.get-next-version.outputs.new-release-version }}
                  git checkout $RELEASE_BRANCH 2>/dev/null || git checkout -b $RELEASE_BRANCH

            - name: pull-request
              run: |
                  RELEASE_BRANCH=release/v${{ needs.get-next-version.outputs.new-release-version }}
                  gh pr create --base main --head $RELEASE_BRANCH  --title 'chore: release  ${{ needs.get-next-version.outputs.new-release-version }}' --body 'Created by Github action'
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
