name: Release

on:
    push:
        branches:
            - main
            - homolog

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - run: corepack enable

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun i

            - name: Run semantic-release
              id: run-semantic-release
              run: bunx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Update homolog branch
              if: ${{ github.ref == 'refs/heads/main' && steps.run-semantic-release.outputs.new-release-published == 'true' }}
              run: |
                  git branch -D homolog
                  git checkout -b homolog
                  git push origin homolog -f

            - name: Delete release branch
              if: ${{ github.ref == 'refs/heads/main' && steps.run-semantic-release.outputs.new-release-published == 'true' }}
              run: |
                  RAW_VERSION=$(echo ${{ steps.run-semantic-release.outputs.new-release-version }} | sed 's/-.*$//')
                  VERSION_BRANCH=release/v$RAW_VERSION
                  git push origin --delete $VERSION_BRANCH || true
