name: Release

on:
    push:
        branches:
            - main
            - homolog

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: corepack enable

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun i

            - name: Run semantic-release
              run: bunx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
